### ISSUE TITLE
dartfmt everything?

### ISSUE THREAD

**Issue by pulyaevskiy** [achilleasa/dart_cassandra_cql#3]
While working #2 I noticed that library's code is not formatted with `dartfmt`.
I use Atom with Dart plugin and it formats files automatically on safe, which is super convenient since I don't have to worry about formatting and code style is guaranteed to be consistent throughout the project.

Would you be opposed to running `dartfmt` on all project files (in `lib/` and `test/`)? This would simplify work on future PRs, as well as other benefits mentioned above.

Of course, I can submit a PR for this, if you're interested.

**Comment by achilleasa** [comment]
Excellent idea! I have passed `lib/`and `test/` through `dartfmt`

**Comment by pulyaevskiy** [comment]
Awesome, thanks!
